<?php

function translate_menu($menu){
  
    $array_menu = [
      'Dashboard'                       =>  'Dasbor', 
      'Admin'                           =>  'Admin',
      'User_Admin'                      =>  'Pengguna Admin',
      'Role_Admin'                      =>  'Peran Admin',
      'Log_Admin'                       =>  'Catatan Admin',
      'Active_Admin'                    =>  'Admin aktif',
      'Report_Admin'                    =>  'Laporan Admin',
      'Transaction'                     =>  'Transaksi',
      'Banking_Transactions'            =>  'Transaksi Bank',
      'User_Bank_Transaction'           =>  'Transaksi Bank Pengguna',
      'Reward_Transaction'              =>  'Transaksi hadiah',
      'Players'                         =>  'Pemain',
      'Active_Players'                  =>  'Pemain Aktif',
      'Report_Players'                  =>  'Laporan Pemain',
      'High_Roller'                     =>  'Roll Tinggi',
      'Registered_Players'              =>  'Pemain terdaftar',
      'Guest'                           =>  'Tamu',
      'Bots'                            =>  'Bot',
      'Play_Report'                     =>  'Laporan permainan',
      'Chip_Players'                    =>  'Chip pemain',
      'Gold_Players'                    =>  'Emas pemain',
      'Point_Players'                   =>  'Poin pemain',
      'Register_Player_ID'              =>  'ID pemain terdaftar',
      'Log_Players'                     =>  'Catatan pemain',
      'Slide_Banner'                    =>  'Slide spanduk',
      'Item'                            =>  'Barang',
      'Table_Gift'                      =>  'Meja Gift',
      'Report_Gift'                     =>  'Laporan Gift',
      'Emoticon'                        =>  'Emoticon',
      'Game'                            =>  'Permainan',
      'Asta-Poker'                      =>  'Asta Poker',
      'Table_Asta_Poker'                =>  'Meja Asta Poker',
      'Category_Asta_Poker'             =>  'Ketegori Asta Poker',
      'Season_Asta_Poker'               =>  'Musim Asta Poker',
      'Season_Reward_Asta_Poker'        =>  'Hadiah Musim Asta Poker',
      'Tournament_Asta_Poker'           =>  'Turnamen Asta Poker',
      'Jackpot_Paytable_Asta_Poker'     =>  'Jackpot Paytable Asta Poker',
      'Big-Two'                         =>  'Big Two',
      'Table_Big_Two'                   =>  'Meja Big Two',
      'Category_Big_Two'                =>  'Kategori Big Two',
      'Season_Big_Two'                  =>  'Musim Big Two',
      'Season_Reward_Big_Two'           =>  'Hadiah Musim Big Two',
      'Tournament_Big_Two'              =>  'Turnamen Big Two',
      'Jackpot_Paytable_Big_Two'        =>  'Jackpot Paytable Big Two',
      'Domino-Susun'                    =>  'Domino susun',
      'Table_Domino_Susun'              =>  'Meja domino susun',
      'Category_Domino_Susun'           =>  'Kategori domino susun',
      'Season_Domino_Susun'             =>  'Musim Domino susun',
      'Season_Reward_Domino_Susun'      =>  'Hadiah musim Domino susun',
      'Tournament_Domino_Susun'         =>  'Turnamen Domino susun',
      'Jackpot_Paytable_Domino_Susun'   =>  'Jakcpot Paytable Domino Susun',
      'Domino-QQ'                       =>  'Domino QQ',
      'Table_Domino_QQ'                 =>  'Meja Domino QQ',
      'Category_Domino_QQ'              =>  'Kategori Domino QQ',
      'Season_Domino_QQ'                =>  'Musim Domino QQ',
      'Season_Reward_Domino_QQ'         =>  'Hadiah Musim Domino QQ',
      'Tournament_Domino_QQ'            =>  'Turnamen Domino QQ',
      'Jackpot_Paytable_Domino_QQ'      =>  'Jackpot Paytable Domino QQ',
      'Game_Setting'                    =>  'Pengaturan permainan',
      'Store'                           =>  'Toko',
      'Best_Offer'                      =>  'Penawaran terbaik',
      'Chip_Store'                      =>  'Toko Chip',
      'Gold_Store'                      =>  'Toko Emas',
      'Goods_Store'                     =>  'Toko Barang',
      'Payment_Store'                   =>  'Toko Pembayaran',
      'Report_Store'                    =>  'Laporan Toko',
      'Notification'                    =>  'Pemberitahuan',
      'Push_Notification'               =>  'Pemberitahuan push',
      'Email_Notification'              =>  'Pemberitahuan Email',
      'FeedBack'                        =>  'Umpan balik',
      'Report_Abuse_Player'             =>  'Laporan penyalahgunaan pemain',
      'Abuse_Transaction_Report'        =>  'Laporan penyalahgunaan transaksi',
      'Feedback_Game'                   =>  'Umpan Balik permainan',
      'Settings'                        =>  'Pengaturan',
      'General_Setting'                 =>  'Pengaturan umum',
      'Reseller'                        =>  'Agen',
      'List_Reseller'                   =>  'Daftar Agen',
      'Reseller-Transaction'            =>  'Transaksi Agen',
      'Request_Transaction'             =>  'Transaksi Permintaan',
      'Report_Transaction'              =>  'Laporan Transaksi',
      'Balance_Reseller'                =>  'Balance Agen',
      'Item_Store_Reseller'             =>  'Toko Agen',
      'Reseller_Rank'                   =>  'Peringkat Agen',
      'Register_Reseller'               =>  'Pendaftaran Agen',
      'Version_Asset_Apk'               =>  'Versi Aset Apk',
      'logout'                          =>  'Keluar'
    ];

    return $array_menu[$menu];
}

?>